import Head from 'next/head'
import styles from '../../styles/Careers.module.css'
import MainLayout from "../../components/layout/MainLayout"
import Image from 'next/image'
import Link from "next/link"
import { useRouter } from "next/router"


export default function Careers() {

    const router = useRouter()
    const jobId = router.query.id

    const jobArr = [
        {
            title: "",
            location: "",
            description: "",
            responsibilities: [
                "", ""
            ],
            experience: [
                "", ""
            ],
            ending: ""
        }
    ]

    return (
        <>
            <Head>
                <title>VEHDE - Careers</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <section id={styles.heroSection} className="heroSection">
                    <div>
                        <div className='container'>
                            <div className='row row-cols-lg-2 gap-5'>
                                <div>
                                    <h1>Careers at VEHDE</h1>
                                </div>
                                <div></div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.reserveCarSection}>
                    <div className='container'>
                        <div className={styles.reserveCarSectionWrapper}>
                            <h2 className='text-center mb-4'>Team Lead, Real Time Analytics</h2>
                            <h4>Long Beach, CA</h4>
                            <p>At VEHDE, our mission is to improve people’s lives with the world’s best transportation. To do this, we start with our own community by creating an open, inclusive, and diverse organization.

                                As the Team Lead you will be responsible for the supervision of the Real-Time team at VEHDE. This position will maintain the internal policies and procedures, support operations and Real Time Analytics, or RTA, analysts in identifying trends, providing input on metric improvements, including forecast versus actuals.</p>
                            <div>
                                <h4>Responsibilities:</h4>
                                <ul>
                                    <li>Drive efficiencies within the RTA and broader Workforce Management team</li>
                                    <li>Manage daily service levels through the analysis of intraday and historical performance</li>
                                    <li>Respond and adjust the plan to trends across multiple geographies and time zones</li>
                                    <li>Provide leadership, coaching, and guidance to the RTA team; hire, train and develop employees</li>
                                    <li>Coordinate cross-functional staffing activities based on intraday trends identified through multiple workforce management systems and operational analysis</li>
                                    <li>Monitor real-time tools to identify trends or issues that impact neighbor and employee experience</li>
                                    <li>Take decisive action to proactively mitigate  service impacting events</li>
                                    <li>Design, develop, and maintain workforce management reporting tools and processes to ensure enduring success.</li>
                                    <li>Develop and maintain daily, weekly, monthly reports across contact centers</li>
                                </ul>
                            </div>
                            <div>
                                <h4>Experience:</h4>
                                <ul>
                                    <li>3+ years of experience in a workforce management role</li>
                                    <li>3+ years of contact center experience</li>
                                    <li>1+ year experience in a supervisory or managerial role</li>
                                    <li>Must be able to work evenings and weekends</li>
                                    <li>Experience with leading cross-functional teams and a demonstrated history of providing solutions to complex problems</li>
                                    <li>Strong quantitative and analytical skills</li>
                                    <li>Excellent interpersonal skills, including strong listening, written and verbal communication with the ability to clearly and professionally communicate with others</li>
                                    <li>Ability to conduct a detailed workforce analysis and use productivity applications to manage and summarize data</li>
                                    <li>Excellent written, grammatical, and verbal communication skills.</li>
                                    <li>Experience with WFN systems such as Nice, Genesys or Calabrio</li>
                                </ul>
                            </div>
                            <p>VEHDE is an equal opportunity/affirmative action employer committed to an inclusive and diverse workplace. All qualified applicants will receive consideration for employment  without regards to race, color, religion, sex, sexual orientation, gender identity, national origin, disability status, protected veteran status or any other basis prohibited by law. We also consider qualified applicants with criminal histories consistent with applicable federal, state and local law. </p>
                        </div>
                    </div>
                </section>
            </MainLayout>
        </>
    )
}