import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import MainLayout from "../../components/layout/MainLayout"


import styles from "../../styles/host/Home.module.css"


import Section03Img01 from "../../assets/img/Host/section-03-img-01.png"
import Section03Img02 from "../../assets/img/Host/section-03-img-02.png"
import Section03Img03 from "../../assets/img/Host/section-03-img-03.png"
import Section08Img01 from "../../assets/img/home-page/section-08-img-01.png"
import Section08Img02 from "../../assets/img/home-page/section-08-img-02.png"
import Section08Img03 from "../../assets/img/home-page/section-08-img-03.png"
import { useState } from "react"


const index = () => {

    const [isIndividual, setIsIndividual] = useState(true)

    return (
        <>
            <Head>
                <title>VEHDE - Host</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <section id={styles.heroSection} className='heroSection'>
                    <div className="py-5">
                        <div className='container'>
                            <div className='row row-cols-lg-2 gap-5'>
                                <div>
                                    <h1>As an individual or a rental company,</h1>
                                    <p>you can list your car for rent with VEHDE, gaining access to our rapidly growing range of customers across the United States.</p>
                                    <h4>Stay ahead!</h4>
                                    <h4>List your car today, as a host.</h4>
                                    <button className='my-btn'>Apply to host</button>
                                </div>
                                <div></div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.section02}>
                    <div className="container">
                        <div>
                            <h2 className="text-center">Signing up to host</h2>
                            <h3 className="text-center">Let’s get started</h3>
                            <form className={styles.formWrapper}>
                                <div className="row row-cols-2 align-items-center">
                                    <label htmlFor="individual" className={`${isIndividual ? "" : `${styles.inactiveTab} ${styles.inactiveLeftTab}`}`} onClick={() => setIsIndividual(true)}>
                                        Individual
                                    </label>
                                    <input type="radio" name="hostType" id="individual" value="individual" hidden />
                                    <label htmlFor="renderCompany" className={`${isIndividual ? `${styles.inactiveTab} ${styles.inactiveRightTab}` : ""}`} onClick={() => setIsIndividual(false)}>
                                        Render Company
                                    </label>
                                    <input type="radio" name="hostType" id="renderCompany" value="render company" hidden />
                                </div>
                                <div>
                                    {
                                        isIndividual ? <>
                                            <div className="row row-cols-1 row-cols-md-2 p-2 mt-4">
                                                <div className="pe-md-2 mb-3 mb-md-0">
                                                    <div className={`d-flex flex-column ${styles.inputGroup}`}>
                                                        <label htmlFor="">First name</label>
                                                        <input type="text" placeholder="Enter your first name" className="" />
                                                    </div>
                                                </div>
                                                <div className="pe-ms-2">
                                                    <div className={`d-flex flex-column ${styles.inputGroup}`}>
                                                        <label htmlFor="">Last name</label>
                                                        <input type="text" placeholder="Enter your last name" className="" />
                                                    </div>
                                                </div>
                                            </div>
                                        </> : <>
                                            <div className="row row-cols-1 row-cols-md-2 p-2 mt-4">
                                                <div className="pe-md-2  mb-3 mb-md-0">
                                                    <div className={`d-flex flex-column ${styles.inputGroup}`}>
                                                        <label htmlFor="">Registered name</label>
                                                        <input type="text" placeholder="Enter your registered name" className="" />
                                                    </div>
                                                </div>
                                                <div className="pe-ms-2">
                                                    <div className={`d-flex flex-column ${styles.inputGroup}`}>
                                                        <label htmlFor="">License number</label>
                                                        <input type="text" placeholder="Enter your license number" className="" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="row row-cols-1 row-cols-md-2 p-2">
                                                <div className="pe-md-2  mb-3 mb-md-0">
                                                    <div className={`d-flex flex-column ${styles.inputGroup}`}>
                                                        <label htmlFor="">Representative</label>
                                                        <input type="text" placeholder="Enter your first name" className="" />
                                                    </div>
                                                </div>
                                                <div className="pe-ms-2">
                                                    <div className={`d-flex flex-column ${styles.inputGroup}`}>
                                                        <label htmlFor="">Representative</label>
                                                        <input type="text" placeholder="Enter your last name" className="" />
                                                    </div>
                                                </div>
                                            </div>
                                        </>
                                    }
                                    <div className="row row-cols-1 row-cols-md-1 p-2">
                                        <div>
                                            <div className={`d-flex flex-column ${styles.inputGroup}`}>
                                                <label htmlFor="">Email</label>
                                                <input type="text" placeholder="Enter your email address" className="" />
                                            </div>
                                        </div>
                                    </div>
                                    <div className="row row-cols-1 row-cols-md-2 p-2">
                                        <div className="pe-md-2 mb-3 mb-md-0">
                                            <div className={`d-flex flex-column ${styles.inputGroup}`}>
                                                <label htmlFor="">Phone</label>
                                                <input type="text" placeholder="Enter your mobile phone number " className="" />
                                            </div>
                                        </div>
                                        <div className="pe-md-2">
                                            <div className={`d-flex flex-column ${styles.inputGroup}`}>
                                                <label htmlFor="">Password</label>
                                                <input type="text" placeholder="Enter your password" className="" />
                                            </div>
                                        </div>
                                    </div>
                                    <div className="row row-cols-1 row-cols-md-2 p-2">
                                        <div className="pe-md-2">
                                            <div className="row row-cols-1 row-cols-md-2">
                                                <div className="pe-md-2">
                                                    <button type="button" style={{ background: "#232636", color: "#FFFFFF", padding: "12px 5px", borderRadius: "25px", border: "none", width: "100%" }} className="mb-2 mb-md-0">
                                                        Driver’s license
                                                    </button>
                                                </div>
                                                <div className="ps-md-2">
                                                    <button type="button" style={{ background: "#FFFFFF", color: "#030719", padding: "12px 5px", borderRadius: "25px", border: "none", width: "100%" }}>
                                                        Availability
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="ps-md-2">
                                        </div>
                                    </div>
                                    <div className="d-flex align-items-center p-2 mt-1 mb-2">
                                        <input type="checkbox" name="" id="" className="me-3 ms-4" />
                                        <p style={{ color: "#898989" }} className="mb-0">I agree to VEHDE’s <span style={{ color: "#DE4F4D" }}>Terms of Use</span> and acknowledge that I have read the <span style={{ color: "#DE4F4D" }}>Privacy Notice.</span></p>
                                    </div>
                                    <div className="p-2">
                                        <button className="my-btn" style={{ width: "100%" }}>Next</button>
                                    </div>
                                    <div className="p-2 mt-1 mb-2 text-center">
                                        <p className="mb-0" style={{ color: "#898989" }}>Already have an account with VEHDE <Link href="" style={{ color: "#DE4F4D" }}>Sign in</Link></p>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </section>
                <section id={styles.section03}>
                    <div className="container">
                        <h2 className="text-center">Host’s benefits with VEHDE</h2>
                        <div className="row row-cols-1 row-cols-md-2 align-items-center mb-md-0 mb-4">
                            <div className="text-center">
                                <Image src={Section03Img01} className="img-fluid" />
                            </div>
                            <div>
                                <h3>Free car listing</h3>
                                <p>It is incredibly free to list your vehicle to rent with VEHDE. With our rapidly growing customers across the United States, you have increased accessibility to potential renters.</p>
                            </div>
                        </div>
                        <div className="row row-cols-1 row-cols-md-2 align-items-center  mb-md-0 mb-4">
                            <div className="order-md-1 order-2">
                                <h3>Free car listing</h3>
                                <p>It is incredibly free to list your vehicle to rent with VEHDE. With our rapidly growing customers across the United States, you have increased accessibility to potential renters.</p>
                            </div>
                            <div className="text-center order-md-2 order-1">
                                <Image src={Section03Img02} className="img-fluid" />
                            </div>
                        </div>
                        <div className="row row-cols-1 row-cols-md-2 align-items-center">
                            <div className="text-center">
                                <Image src={Section03Img03} className="img-fluid" />
                            </div>
                            <div>
                                <h3>Free car listing</h3>
                                <p>It is incredibly free to list your vehicle to rent with VEHDE. With our rapidly growing customers across the United States, you have increased accessibility to potential renters.</p>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.section08}>
                    <div className="container">
                        <div className="wrapper">
                            <h2 className='text-center'>Mask and Safety</h2>
                            <div className="row row-cols-lg-3 row-cols-1 align-items-center">
                                <div className="col p-3">
                                    <div className="text-center d-flex flex-column align-items-center justify-content-between">
                                        <Image src={Section08Img01} alt="Car in hand" />
                                        <h3>Your safety, our no 1 priority.</h3>
                                        <p>We are fully committed to your safety, even as our innovative strategies help enhance your accessibility to mobility of greater value to your productivity.</p>
                                    </div>
                                </div>
                                <div className="col p-3">
                                    <div className="text-center d-flex flex-column align-items-center justify-content-between">
                                        <Image src={Section08Img02} alt="Car in hand" />
                                        <h3>Mask & Social Safety</h3>
                                        <p>With your support, when you observe safety procedures, every day, we protect our great asset –Health.</p>
                                        <Link href="MaskSocialSafety" className='d-block' style={{ paddingBottom: "15px" }}>Learn more about mask and social safety</Link>
                                    </div>
                                </div>
                                <div className="col p-3">
                                    <div className="text-center d-flex flex-column align-items-center justify-content-between">
                                        <Image src={Section08Img03} alt="Car in hand" />
                                        <h3>COVID-19 Vaccine</h3>
                                        <p>Let’s crunch the virus! Our commitment to vaccination moves us closer to full recovery in our various communities.</p>
                                        <Link href="VaccinationProgram">Learn more about vaccination program</Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </MainLayout>
        </>
    )
}

export default index