import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import MainLayout from "../components/layout/MainLayout"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  return (
    <>
      <Head>
        <title>VEHDE - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <section id={styles.heroSection} className='py-5'>
          <div className='container'>
            <div className='row row-cols-md-2 gap-5'>
              <div>
                <h1>Explore the VEHDE’s world of car sharing innovation</h1>
                <div className='d-flex gap-3 align-items-center mt-5'>
                  <button className='my-btn'>Apply To Host</button>
                  <button className='my-btn-outline'>Rent A Car</button>
                </div>
              </div>
              <div></div>
            </div>
          </div>
        </section>
      </MainLayout>
    </>
  )
}
