import Head from 'next/head'
import React from 'react'
import MainLayout from '../components/layout/MainLayout'
import styles from "../styles/MaskSocialSafety.module.css"

const MaskSocialSafety = () => {
    return (
        <>
            <Head>
                <title>VEHDE - Mask & Social Safety</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <section id={styles.heroSection}>
                    <h1>Test</h1>
                </section>
            </MainLayout>
        </>
    )
}

export default MaskSocialSafety