import Head from 'next/head'
import styles from '../styles/SmartGuid2.module.css'
import MainLayout from "../components/layout/MainLayout"
import Image from 'next/image'
import Link from "next/link"
import "react-datepicker/dist/react-datepicker.css";

import RightArrow from "../assets/img/right-arrow.png"
import section03Img from "../assets/img/SmartGuid2/section03Img.png"
import section04Img from "../assets/img/SmartGuid2/section04Img.png"


export default function SmartGuid2() {

    return (
        <>
            <Head>
                <title>VEHDE - Smart Guid 2</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <section id={styles.heroSection} className='py-5'>
                    <div className='container'>
                        <div className='row row-cols-lg-2 gap-5'>
                            <div>
                                <h1>Smart guide</h1>
                            </div>
                            <div></div>
                        </div>
                    </div>
                </section>
                <section id={styles.section02}>
                    <div className="container">
                        <div className="wrapper">
                            <div className='text-center mb-4'>
                                <h2>How VEHDE works</h2>
                                <p>
                                    VEHDE works in six (6) major steps, carefully designed to enhance people’s productivity by improving their accessibility to mobility.
                                </p>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.section03} className="mb-5">
                    <div className="container">
                        <div className="wrapper">
                            <div className="row row-cols-lg-2 row-cols-1 align-items-center">
                                <div className="col p-5">
                                    <Image src={section03Img} alt="" className='img-fluid' />
                                </div>
                                <div className="col">
                                    <h2>What sets up apart</h2>
                                    <p>At VEHDE, we treat your payment for car’s rentals as an investment. That is why we are here to serve you better, in a way more productive manner.</p>
                                    <p>
                                        We developed our strategy based on our extensive experience in the transportation industry, and this is because we understand how sustainability continues to define the future of the transportation industry
                                    </p>
                                    <p>
                                        Our innovative strategy, with a great emphasis on sustainability, is carefully designed to optimize your return on investment.
                                    </p>
                                    <div className="d-flex align-items-center gap-3">
                                        <Link href="#">Learn more about your unique benefits with VEHDE</Link> <Image src={RightArrow} alt="" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.section04} className="my-5">
                    <div className="container">
                        <div className="wrapper">
                            <div className="row row-cols-lg-2 row-cols-1 align-items-center">
                                <div className="col">
                                    <h2>Flexibility that supports you and your business</h2>
                                    <div className="row row-cols-md-2 row-cols-1 my-5">
                                        <div className="col d-flex align-items-center gap-2 mb-3">
                                            <input type="checkbox" name="manufacturers" id="Manufacturers" defaultChecked />
                                            <label htmlFor="Manufacturers">Manufacturers</label>
                                        </div>
                                        <div className="col d-flex align-items-center gap-2 mb-3">
                                            <input type="checkbox" name="corporateOrganizations" id="Corporate-organizations" />
                                            <label htmlFor="Corporate-organizations">Corporate organizations</label>
                                        </div>
                                        <div className="col d-flex align-items-center gap-2">
                                            <input type="checkbox" name="individuals" id="Individuals" />
                                            <label htmlFor="Individuals">Individuals</label>
                                        </div>
                                        <div className="col d-flex align-items-center gap-2">
                                            <input type="checkbox" name="manufacturers" id="Manufacturers" />
                                            <label htmlFor="Manufacturers">Manufacturers</label>
                                        </div>
                                    </div>
                                    <div className="d-flex align-items-center gap-3">
                                        <Link href="#" className='my-btn'>Rent a Car</Link>
                                        <Link href="#" className='my-btn-outline'>Apply to host</Link>
                                    </div>
                                </div>
                                <div className="col p-5">
                                    <div className='text-center'>
                                        <Image src={section04Img} alt="" className='img-fluid' />
                                        <button className='my-btn mx-auto mt-4 mb-2'>Submit Work</button>
                                        <p>
                                            General Information Request Tool
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </MainLayout>
        </>
    )
}