import Head from 'next/head'
import React from 'react'
import MainLayout from '../components/layout/MainLayout'
import styles from "../styles/SmartGuid.module.css"

import { Navigation, Autoplay, Pagination } from 'swiper';
import { Swiper, SwiperSlide } from "swiper/react"
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

import Image from 'next/image'
import Link from 'next/link'

import Section02Img01 from "../assets/img/SmartGuid/section-02-img-01.png"

const SmartGuid = () => {

    const pagination = {
        clickable: true,
        renderBullet: function (index, className) {
            return '<span class="' + className + '">' + (index + 1) + "</span>";
        },
    };

    return (
        <>
            <Head>
                <title>VEHDE - Smart Guid</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout>
                <section id={styles.heroSection}>
                    <div>
                        <div className="container">
                            <div className="wrapper">
                                <div className="row align-items-center">
                                    <div className="col-lg-5 mb-lg-0 mb-5">
                                        <h1>Smart guide</h1>
                                        <h2>Unique benefits with VEHDE</h2>
                                        <p>
                                            You, too, should have access to cost-effective rental cars without the liabilities that are associated with conventional cars’ ownership arrangements.
                                        </p>
                                        <h4>
                                            Before you buy/lease/rent a car, or book your next ride, TRY VEHDE!
                                        </h4>
                                        <div className="d-flex flex-xl-row flex-column gap-3">
                                            <Link href="#" className='my-btn'>Rent a Car</Link>
                                            <Link href="#" className='my-btn-outline'>Apply to host</Link>
                                        </div>
                                    </div>
                                    <div className="col-lg-7 text-center">
                                        {/* <Image src={HeroSectionImg} alt="Patent Vaccination Program Image" className='img-fluid' /> */}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section id={styles.section02} className="SmartGuidSection02">
                    <div className="container">
                        <div className="wrapper">
                            <Swiper
                                spaceBetween={30}
                                centeredSlides={false}
                                autoplay={{
                                    delay: 3000,
                                    disableOnInteraction: false,
                                }}
                                navigation={true}
                                pagination={pagination}
                                modules={[Autoplay, Navigation, Pagination]}
                                slidesPerView={1}
                            >
                                <SwiperSlide className='row row-cols-lg-2 row-cols-1 gap-lg-0 gap-4 align-items-center'>
                                    <div className="col">
                                        <Image src={Section02Img01} alt="Air Bnb" className='img-fluid' />
                                    </div>
                                    <div className="col">
                                        <h2>High quality car listings for rentals at competitive prices.</h2>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide className='row row-cols-lg-2 row-cols-1 gap-lg-0 gap-4 align-items-center'>
                                    <div className="col">
                                        <Image src={Section02Img01} alt="Air Bnb" className='img-fluid' />
                                    </div>
                                    <div className="col">
                                        <h2>High quality car listings for rentals at competitive prices.</h2>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide className='row row-cols-lg-2 row-cols-1 gap-lg-0 gap-4 align-items-center'>
                                    <div className="col">
                                        <Image src={Section02Img01} alt="Air Bnb" className='img-fluid' />
                                    </div>
                                    <div className="col">
                                        <h2>High quality car listings for rentals at competitive prices.</h2>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide className='row row-cols-lg-2 row-cols-1 gap-lg-0 gap-4 align-items-center'>
                                    <div className="col">
                                        <Image src={Section02Img01} alt="Air Bnb" className='img-fluid' />
                                    </div>
                                    <div className="col">
                                        <h2>High quality car listings for rentals at competitive prices.</h2>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide className='row row-cols-lg-2 row-cols-1 gap-lg-0 gap-4 align-items-center'>
                                    <div className="col">
                                        <Image src={Section02Img01} alt="Air Bnb" className='img-fluid' />
                                    </div>
                                    <div className="col">
                                        <h2>High quality car listings for rentals at competitive prices.</h2>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide className='row row-cols-lg-2 row-cols-1 gap-lg-0 gap-4 align-items-center'>
                                    <div className="col">
                                        <Image src={Section02Img01} alt="Air Bnb" className='img-fluid' />
                                    </div>
                                    <div className="col">
                                        <h2>High quality car listings for rentals at competitive prices.</h2>
                                    </div>
                                </SwiperSlide>
                                <SwiperSlide className='row row-cols-lg-2 row-cols-1 gap-lg-0 gap-4 align-items-center'>
                                    <div className="col">
                                        <Image src={Section02Img01} alt="Air Bnb" className='img-fluid' />
                                    </div>
                                    <div className="col">
                                        <h2>High quality car listings for rentals at competitive prices.</h2>
                                    </div>
                                </SwiperSlide>
                            </Swiper>
                        </div>
                    </div>
                </section>
            </MainLayout>
        </>
    )
}

export default SmartGuid